Running in wrapper mode for '20114'

Running python job.

{u'nfeatures': array([56]), u'bow_size': array([540]), u'svm_gamma': array([-1.91623625]), u'edgeThreshold': array([ 50.]), u'svm_C': array([ 2.482552]), u'sigma': array([ 1.40289408]), u'contrastThreshold': array([ 0.00907498])}
----- Fold: 0
Testing with 951 pos 1473 neg
Training with 3349 pos 5490 neg
--- Gather features---
--- Train BOW---
--- Make hists---
--- No histograms for 32 images ---
--- Fit model---
/usr/local/lib/python2.7/dist-packages/sklearn/svm/base.py:176: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  (self.gamma == 'auto')):
/usr/local/lib/python2.7/dist-packages/sklearn/svm/base.py:179: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  elif self.gamma == 'auto':
--- Overall training model took 1805.30027509 ---
--- No histograms for 23 images ---
TP: 713 FP: 270 TN 1203 FN: 238
--- kfold: 0, accuracy: 0.790429042904, youden*coverage: 0.561063114397
----- Fold: 1
Testing with 900 pos 1372 neg
Training with 3400 pos 5591 neg
--- Gather features---
--- Train BOW---
--- Make hists---
--- No histograms for 49 images ---
--- Fit model---
--- Overall training model took 1773.11355877 ---
--- No histograms for 6 images ---
TP: 658 FP: 205 TN 1167 FN: 242
--- kfold: 1, accuracy: 0.803257042254, youden*coverage: 0.580158037226
----- Fold: 2
Testing with 785 pos 1569 neg
Training with 3515 pos 5394 neg
--- Gather features---
--- Train BOW---
--- Make hists---
--- No histograms for 44 images ---
--- Fit model---
--- Overall training model took 1794.49544883 ---
--- No histograms for 11 images ---
TP: 571 FP: 264 TN 1305 FN: 214
--- kfold: 2, accuracy: 0.796941376381, youden*coverage: 0.556515746806
----- Fold: 3
Testing with 889 pos 1174 neg
Training with 3411 pos 5789 neg
--- Gather features---
--- Train BOW---
----------------------------------------
Problem running the job:
(<type 'exceptions.SystemExit'>, SystemExit(0,), <traceback object at 0x7f0c236cfab8>)
Traceback (most recent call last):
  File "/home/hans/wart-detection/spearmint/spearmint/spearmint/runner.py", line 41, in job_runner
    elif job.language == PYTHON: run_python_job(job)
  File "/home/hans/wart-detection/spearmint/spearmint/spearmint/runner.py", line 131, in run_python_job
    result = module.main(job.id, params)
  File "/home/hans/wart-detection/bay_opt/experiment.py", line 38, in main
    print params
  File "/home/hans/wart-detection/analyze_training.py", line 44, in cross_validate_with_participants
    model, vocabulary = train_model(train_set_pos, train_set_neg, detector_name, descriptor_name, dect_params, n_features, bow_size, k, model_params=model_params)
  File "/home/hans/wart-detection/analyze_training.py", line 121, in train_model
    
  File "/home/hans/wart-detection/analyze_training.py", line 180, in train_bagofwords
    def train_bagofwords(features, bow_size, norm=cv2.NORM_L2):
  File "/home/hans/wart-detection/spearmint/spearmint/bin/../spearmint/main.py", line 323, in sigint_handler
    sys.exit(0)
SystemExit: 0
None
----------------------------------------
Process Process-525:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hans/wart-detection/spearmint/spearmint/spearmint/runner.py", line 61, in job_runner
    job      = load_job(job_file)
  File "/home/hans/wart-detection/spearmint/spearmint/spearmint/helpers.py", line 76, in load_job
    fh = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: u'/home/hans/wart-detection/bay_opt/jobs/00020114.pb'
