Running in wrapper mode for '20074'

Running python job.

{u'nfeatures': array([50]), u'bow_size': array([660]), u'svm_gamma': array([ 0.04272097]), u'edgeThreshold': array([ 50.]), u'svm_C': array([ 3.]), u'sigma': array([ 0.74977937]), u'contrastThreshold': array([ 0.01309006])}
----- Fold: 0
Testing with 234 pos 1473 neg
Training with 1277 pos 5490 neg
--- Gather features---
--- Train BOW---
--- Make hists---
--- No histograms for 154 images ---
--- Fit model---
/usr/local/lib/python2.7/dist-packages/sklearn/svm/base.py:176: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  (self.gamma == 'auto')):
/usr/local/lib/python2.7/dist-packages/sklearn/svm/base.py:179: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  elif self.gamma == 'auto':
--- Overall training model took 1709.21343589 ---
--- No histograms for 102 images ---
TP: 81 FP: 143 TN 1330 FN: 153
--- kfold: 0, accuracy: 0.826596367897, exp_mean*coverage: 0.354877897482
----- Fold: 1
Testing with 361 pos 1372 neg
Training with 1150 pos 5591 neg
--- Gather features---
--- Train BOW---
--- Make hists---
--- No histograms for 212 images ---
--- Fit model---
--- Overall training model took 1709.10307813 ---
--- No histograms for 44 images ---
TP: 138 FP: 109 TN 1263 FN: 223
--- kfold: 1, accuracy: 0.808424697057, exp_mean*coverage: 0.409917225711
----- Fold: 2
Testing with 292 pos 1569 neg
Training with 1219 pos 5394 neg
--- Gather features---
--- Train BOW---
--- Make hists---
--- No histograms for 194 images ---
--- Fit model---
--- Overall training model took 1673.91030192 ---
--- No histograms for 62 images ---
TP: 111 FP: 118 TN 1451 FN: 181
--- kfold: 2, accuracy: 0.839333691564, exp_mean*coverage: 0.408148031473
----- Fold: 3
Testing with 321 pos 1174 neg
Training with 1190 pos 5789 neg
--- Gather features---
--- Train BOW---
----------------------------------------
Problem running the job:
(<type 'exceptions.SystemExit'>, SystemExit(0,), <traceback object at 0x7fae19aaa290>)
Traceback (most recent call last):
  File "/home/hans/wart-detection/spearmint/spearmint/spearmint/runner.py", line 41, in job_runner
    elif job.language == PYTHON: run_python_job(job)
  File "/home/hans/wart-detection/spearmint/spearmint/spearmint/runner.py", line 131, in run_python_job
    result = module.main(job.id, params)
  File "/home/hans/wart-detection/bay_opt_warts/experiment.py", line 39, in main
    kappa = cross_validate_with_participants(5, parts, dect_params=dect_params, bow_size=params['bow_size'], model_params=model_params, cream=False)
  File "/home/hans/wart-detection/train.py", line 55, in cross_validate_with_participants
    model, vocabulary = train_model(train_set_pos, train_set_neg, detector_name, descriptor_name, dect_params, n_features, bow_size, k, model_params=model_params, classifier=classifier)
  File "/home/hans/wart-detection/train.py", line 141, in train_model
    vocabulary = train_bagofwords(features, bow_size)
  File "/home/hans/wart-detection/train.py", line 204, in train_bagofwords
    vocabulary = bow.cluster()
  File "/home/hans/wart-detection/spearmint/spearmint/bin/../spearmint/main.py", line 323, in sigint_handler
    sys.exit(0)
SystemExit: 0
None
----------------------------------------
Job file reloaded.
Could not find value in output file.
Job failed in 6778.37 seconds.
